on:
  workflow_call:
    inputs:
      Pr_Number:
        type: string
        required: true
      C_Version:
        type: string
        required: true
      S_Version:
        type: string
        required: true
      Repository:
        type: string
        required: true
jobs:
  update-pr-body:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout Code
      #   uses: actions/checkout@v3

      - name: Print value 
        run: |
          echo "The Pull Request Number is ${{ github.event.inputs.Pr_Number }}"
          echo "The Pull Request Number is ${{ github.event.inputs.C_Version }}"
          echo "The Pull Request Number is ${{ github.event.inputs.S_Version }}"
          echo "The Pull Request Number is ${{ github.event.inputs.Repository }}"

