name: Manual Workflow

on:
  pull_request:
    types: [opened, labeled, closed]

env:
  Pr_Number: "11"
#

jobs:
  call-workflow:
    uses: ./.github/workflows/image.yml #ravikumara004/protectbranch/.github/workflows/renew.yaml@v1.0.0    #./.github/workflows/re.yaml
    with:
      Pr_Number: ${{ env.project1 }}
    secrets:
      token: ${{ secrets.MY_TOKEN }} # Correctly use the secret
