name: Docker Image CI

on:
 workflow_dispatch:


jobs:

  call-workflow-in-local-repo:
    uses: ./.github/workflows/docker.yaml
    

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
